print('===== DESAFIO 15 =====')
dia = int(input('Quantos dias alugados? '))
km = float(input('Quantos km rodados? '))
preco = (dia * 60) + (km * 0.15)
print('O total a pagar e de {:.2f}'.format(preco))